apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- postgres.yaml
- deployment.yaml
namespace: weather-app
configMapGenerator:
- literals:
  - CITY=Mississauga
  - LOG_LEVEL=INFO
  - UPDATE_INTERVAL=300
  name: weather-app-config
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: weather-app
    app.kubernetes.io/part-of: weather-monitoring

