---
apiVersion: v1
kind: Secret
metadata:
  name: weather-api-secret
  namespace: weather-app
type: Opaque
data:
  # Base64 encoded API key
  # Example: echo -n "your_weatherapi_key_here" | base64
  api-key: eW91cl93ZWF0aGVyYXBpX2tleV9oZXJl
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: weather-app
type: Opaque
data:
  # Base64 encoded username and password
  # Example: echo -n "postgres" | base64
  # Example: echo -n "your_secure_password" | base64
  username: cG9zdGdyZXM=
  password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
  namespace: weather-app
type: Opaque
data:
  # Base64 encoded password for grafana_reader user
  # Should match the password in init-db-configmap.yaml
  # Example: echo -n "grafana_secure_password" | base64
  password: Z3JhZmFuYV9zZWN1cmVfcGFzc3dvcmQ=
